Ability install external packages
Currently only support ZIP files

diff --git a/bin/curl-checksum b/bin/curl-checksum
--- a/bin/curl-checksum
+++ b/bin/curl-checksum
@@ -5,53 +5,56 @@ usage () {
 Download and SHA-256 checksum-validate a file.
 
 The requested URL is validated against the given SHA-256 checksum before
-the contents are returned. If the file does not match the checkum, the program
+the contents are returned. If the file does not match the checksum, the program
 exits with error code 1.
 
 If no checksum argument is given, prints out the current checksum for the
 requested URL to STDOUT.
 
 Usage:
-  $ ${0##*/} [options] <url> [sha-256] [curl-options]
+  $ ${0##*/} [options] <url> [output-file] [sha-256]
 
 Options:
   -h, --help     Print this message
   -v, --version  Print version number
 
 Examples:
-  $ ${0##*/} https://localhost/file.zip
+  $ ${0##*/} https://localhost/file.zip file.zip
   > ecf701f727d9e2d77c4aa49ac6fbbcc997278aca010bddeeb961c10cf54d435a
-  $ ${0##*/} https://localhost/file.zip 788eb2...be65 > file.zip
+  $ ${0##*/} https://localhost/file.zip file.zip 788eb2...be65
 EOF
 }
 
 main () {
-  local url sha256 contents checksum
+  local url sha256 checksum file
 
   url="${1:-}"
-  shift
+  file="${2:-}"
+  sha256="${3:-}"
 
-  if [ "${1:-}" ] && ! [ "${1:0:1}" = "-" ]; then
-    sha256="$1"
-    shift
+  if ! [ "$url" ] || ! [ "$file" ]; then
+    echo "URL and output file are required." >&2
+    exit 1
   fi
 
-  contents="$(curl -qfsSL "$@" -- "$url")" || exit 1
-  checksum="$(printf '%s' "$contents" | shasum -a 256 | awk '{print $1}')" || exit 1
+  curl -qfSL --progress-bar --output "$file" -- "$url" || exit 1
 
-  if ! [ "${sha256:-}" ]; then
+  checksum="$(shasum -a 256 -- "$file" | awk '{print $1}')" || exit 1
+
+  if ! [ "$sha256" ]; then
     echo "$checksum"
+    rm "$file" || exit 1
     exit 0
   fi
 
   if [ "$checksum" = "$sha256" ]; then
-    echo "$contents"
     exit 0
   fi
 
   echo "SHA-256 checksum mismatch." >&2
   echo "⋯ Expected: $sha256" >&2
   echo "⋯ Received: $checksum" >&2
+  rm "$file" || exit 1
   exit 1
 }
 
diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -34,6 +34,9 @@ Commands:
   $app_name install-deps
   Install third-party dependencies through package managers.
 
+  $app_name install-packages
+  Install packages.
+
   $app_name lint
   Lint codebase.
 
@@ -188,6 +191,7 @@ main () {
     dump) dump ;;
     install) install ;;
     install-deps) install_dependencies ;;
+    install-packages) install_packages ;;
     lint) lint ;;
     pull) pull ;;
     prefix) prefix ;;
@@ -212,6 +216,70 @@ install () {
       link "$line"
     fi
   done < "$directory/.dotfile-links"
+}
+
+install_packages () {
+  local line name checkum url current_checksum download package meta file
+
+  while read -r line; do
+    if ! [ "$line" ]; then
+      continue
+    fi
+
+    name="$(echo "$line" | cut -d' ' -f1)"
+    checksum="$(echo "$line" | cut -d' ' -f2)"
+    url="$(echo "$line" | cut -d' ' -f3)"
+    file="__download.zip"
+    download="packages/$name/$file"
+    package="packages/$name"
+    meta="packages/$name.meta"
+
+    if ! [ "$url" ]; then
+      continue
+    fi
+
+    if [ -e "$meta" ]; then
+      current_checksum="$(cut -d' ' -f2 < "$meta")"
+
+      if [ "$checksum" = "$current_checksum" ]; then
+        log "${blue}↯${reset} Package ${yellow}$name${reset} is up-to-date"
+        log "${blue}·${reset} Checksum: $current_checksum"
+        continue
+      fi
+    fi
+
+    log "${blue}↯${reset} Installing ${yellow}$name${reset} to ${yellow}$package${reset}..."
+    log "${blue}·${reset} URL: $url"
+    log "${blue}·${reset} Checksum: $checksum"
+
+    rm -rf "$package" > /dev/null \
+      || fatal "${red}✘${reset} Failed to remove old ${yellow}$package${reset}"
+
+    mkdir -p "$package" > /dev/null \
+      || fatal "${red}✘${reset} Failed to create directory ${yellow}$package${reset}"
+
+    curl-checksum "$url" "$download" "$checksum" \
+      || fatal "${red}✘${reset} Downloading file failed"
+
+    cd "$package" > /dev/null \
+      || fatal "${red}✘${reset} Navigating to directory ${yellow}$package${reset} failed"
+
+    unzip "$file" > /dev/null \
+      || fatal "${red}✘${reset} Extracting ${yellow}$package${reset} failed"
+
+    rm "$file" > /dev/null \
+      || fatal "${red}✘${reset} Removing ${yellow}$package${reset} failed"
+
+    cd ../.. > /dev/null \
+      || fatal "${red}✘${reset} Failed navigating back"
+
+    echo "$line" > "$meta" \
+      || fatal "${red}✘${reset} Failed to create file ${yellow}$meta${reset}"
+  done < "$directory/.dotfile-packages"
+
+  chmod +x packages/*/bin/*
+
+  log "${green}✓${reset} Packages installed"
 }
 
 install_dependencies () {
