git-keyword-cherry-pick fixes and improvements

diff --git a/bin/git-keyword-cherry-pick b/bin/git-keyword-cherry-pick
--- a/bin/git-keyword-cherry-pick
+++ b/bin/git-keyword-cherry-pick
@@ -25,7 +25,34 @@ Examples:
 EOF
 }
 
+msg () {
+  local message
+
+  for message in "$@"; do
+    echo "$message"
+  done
+}
+
+err () {
+  msg "$@" >&2
+}
+
+fatal () {
+  err "$@"
+  exit 1
+}
+
 main () {
+  local branch
+
+  if [ "$#" -eq 0 ]; then
+    fatal "Branch is required."
+  fi
+
+  branch="${1:-}"
+
+  shift 1
+
   # shellcheck disable=SC2046
   set -- $(hashes "$@")
 
@@ -57,7 +84,7 @@ commit() {
 }
 
 prompt () {
-  local answer
+  local answer selection
 
   read -r -p "Cherry-pick commit row (1-n, all, exit): " answer
 
@@ -65,52 +92,56 @@ prompt () {
     exit 0
   fi
 
-  # shellcheck disable=SC2046
-  cherry-pick $(selection "$answer" "$@")
+  selection "$answer" "$@" || fatal
+
+  cherry-pick "${selection[@]}"
 }
 
 selection () {
-  local min max row i
+  local min max row i hash
+
+  selection=()
 
   row="$1"
 
   shift 1
 
   case "$row" in
-    a*|"") ;;
+    a*) ;;
     *-*)
       min="$(echo "$row" | awk -F '-' '{print $1}')"
       max="$(echo "$row" | awk -F '-' '{print $2}')"
       ;;
-    *)
-      echo "${@:$row:1}"
-      return
+    [0-9]*)
+      min="$row"
+      max="$row"
       ;;
+    *) return 1 ;;
   esac
 
   min="${min:-1}"
   max="${max:-$#}"
 
   for ((i=min;i<=max;i++)); do
-    echo "${@:$i:1}"
+    hash="${*:$i:1}"
+
+    if ! [ "$hash" ]; then
+      return 1
+    fi
+
+    selection+=("$hash")
   done
+
+  return 0
 }
 
 cherry-pick () {
   local hash
 
-  if [ "$#" -gt 1 ]; then
-    for hash in "$@"; do
-      git cherry-pick -x "$hash"
-      false || skip || return 1
-    done
-
-    return 0
-  fi
-
-  if [ "$#" -eq 1 ]; then
-    git cherry-pick -x "$1" || return 1
-  fi
+  for hash in "$@"; do
+    msg "Cherry-picking $hash..."
+    git cherry-pick -x "$hash" || skip || return 1
+  done
 
   return 1
 }
@@ -118,7 +149,7 @@ cherry-pick () {
 skip () {
   local answer
 
-  echo "Failed to cherry-pick $hash" >&2
+  err "Failed to cherry-pick $hash"
   commit "$hash" >&2
   read -r -p "Skip and continue from the next commit (Yes/no)? " answer
 
@@ -129,11 +160,7 @@ skip () {
 }
 
 hashes () {
-  local args branch option
-
-  branch="${1:-}"
-
-  shift 1
+  local args option
 
   args=()
 
